### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by wildmaster84** [DRE2N/Asteria#1]
While running the plugin for about a few weeks, me and a few of my friends have started having connections issues on the server. The ping for everyone was pretty low. i removed the plugin and the connection issues were fixed, will there be any sort of patch for this? also the images breaks on a server restart so the plugin has to be reloaded to fix them.

**Comment by Malfrador** [comment]
I am a bit confused. Asteria doesn't have anything to do with images? It also doesn't interact with networking in any way, just spawning display entities and changing their transformation

**Comment by wildmaster84** [comment]
Sorry, i somehow confused this plugin with something else xd
